# Generated by Django 4.2.1 on 2023-06-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0004_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
