# Generated by Django 4.2.1 on 2023-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default='', upload_to='message/memories'),
        ),
    ]
