# Generated by Django 4.2.1 on 2023-06-15 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0006_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='postdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
