# Generated by Django 4.2.1 on 2023-06-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0007_message_postdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='categories',
            field=models.CharField(default='begining of an era', max_length=25),
        ),
    ]
