# Generated by Django 4.2.1 on 2023-06-17 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anonymous', '0013_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
