# Generated by Django 4.2.1 on 2023-06-17 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anonymous', '0014_message_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='book',
            field=models.ManyToManyField(related_name='blog_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
